name: caxapok
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/Yobari-Timeliners/caxapok

environment:
  sdk: ^3.10.0

dependencies:
  collection: ^1.19.1
  meta: ^1.18.1


dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  very_good_analysis: ^10.0.0
